### Site Settings ###
title               : Azka Radinka
description         : >-
                      I am Azka, currently pursuing six-months machine learning course of study in Google Bangkit 2021
baseurl             : ""                     # Change to empty quotes if you are hosting your site at <your-username>.github.io directly
repository          : radinka-data/radinka-data.github.io     # Change to <your-username>/<your-username>.github.io (or remove it if you don't need remote projects)
remote_theme        : YoussefRaafatNasry/portfolYOU


### Plugins ###
plugins:
  - jemoji


### Navbar Settings ###
nav_exclude:                                            # The following paths are excluded from navbar
  - pages/tags.html
  - pages/404.html
  - pages/index.md


### Author Info ###
author:
  name              : Azka Radinka
  image             : https://lh3.googleusercontent.com/bClCnFwDK9yA1nxHoMiPOaPFRf9gkCmpn5KrBk6A2iDS3Z5MAUBVzfaFK2VN2VKOpT79Io3_CQgv0aj4CCIT74GPeqwEhjjlx4JVhO9oR4pl4QpPDutZ3yqdYy1V2eGknCoVYH-m7X31Nws33nOawrD48oEPFZXyqxoKE_2tHbxe3uIFhj-AOP7XMWyw0d4VofM8atBxqbe1urAT_t0LRY2PyP_SghQzPwkY0r7xJZYqbc2CmWooNYOwCtyVl9h8SfWHGoqBcm3CK8JJ41e5NAhly2dQwdZul_HQVA8_QyDJnnMmRj1yMkyi0Jcz--kGZdinFaJTehwjiTh32ym1TvjWAdA52uC830cYCIeaRpt3fZvpEJJQL3suZh1dR7S2in6I_eZqcjNAcbTFIQU4EqJKos8i55lzQX9fJ-0kcE66aIltUNvU_EKbVhxtLTqfRhqceQhPqbM1OLJt62PqEolMOMW_D59-UY6XO-f3JMOUt2yaVf5OZbKeUYi_UP3ktEQYnkx7k0bCX4_0bNmh9NF1hWBTeCST4oiSRwMSrfGv0xPxZ9RLOUrxflZJ2uoYvu39oUBxLOf7DcpiDcV06o6gwFvMfGbJT3tFoSeJ9uwmW8uQXmL-RQktaVWkxqXn8gH8e1cWHbDDprTdxf2JNfjgrzdxANyT36AstRPa_C0Qotj4Rt8aeg4B_WSTtuxQ-A9kTo7LNaVOPBjmBl5SdGVZ-A=s695-no?authuser=0
# behance           : your_username
# dribbble          : your_username
  email             : azkaradinka@gmail.com
#  facebook          : your_username
  github            : aradinka
# gitlab            : your_username
# instagram         : your_username
# kaggle            : your_username
  linkedin          : aradinka
#  medium            : your_username
# soundcloud        : your_username
# spotify           : your_username
# stackoverflow     : your_user_id
# tumblr            : your_username.tumblr.com
# twitch            : your_username
#  twitter           : your_username
# vimeo             : your_username
# youtube           : your_channel_name
# keybase           : your_username


### Posts ###
permalink: /blog/:title


### Collections ###
collections:
  projects:
    output: true
    permalink: /projects/:name
  elements:                                             # For Documentation Only
    output: true                                        # For Documentation Only


### Disqus ###
disqus:
  shortname: your-short-name-disqus                     # Your website Shortname on disqus


### Analytics ###
analytics:
  enabled: false                                        # Set true to enable analytics
  google:
    tracking_id: your-google-tracking-id


### Defaults for collections ###
defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "page"
  - scope:                                              # For Documentation Only
      path: ""                                          # For Documentation Only
      type: "elements"                                  # For Documentation Only
    values:                                             # For Documentation Only
      layout: "element"                                 # For Documentation Only
  - scope:
      path: ""
      type: "posts"
    values:
      comments: false                                   # Set to true to enable disqus comments

### Exclude from processing ###
exclude:
  - README.md
  - CONTRIBUTING.md
  - LICENSE
  - "*.log"
